version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "LunchtimeUsers"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-168a19vznprca"
s3_prefix = "LuchtimeUsers"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
